[[cloud_folders]]
name = "wallpapers"
folder_path = 'C:\Users\Stepan\Pictures\Wallpapers'

[[cloud_folders]]
name = "code"
folder_path = 'C:\Users\Stepan\Code'

[[clouds]]
name = "cloud1"
password = "wallpaper"
password_changed_at = "2025-10-23T08:33:36.617591300Z"
jwt_secret = "cloud-cloud1-secret-4ed078404a840369"

[[clouds.cloud_folders]]
name = "wallpapers"
folder_path = 'C:\Users\Stepan\Pictures\Wallpapers'

[[clouds.cloud_folders]]
name = "code"
folder_path = 'C:\Users\Stepan\Code'

[[clouds]]
name = "codecloud"
password = "11111111"
password_changed_at = "2025-10-23T08:34:06.961703Z"
jwt_secret = "cloud-codecloud-secret-cb236e3c4b2d2ef9"

[[clouds.cloud_folders]]
name = "wallpapers"
folder_path = 'C:\Users\Stepan\Pictures\Wallpapers'

[[clouds.cloud_folders]]
name = "code"
folder_path = 'C:\Users\Stepan\Code'
