cloudfolders_path = "~/.cloudhost/cloudfolders"
server_port = 3000
password_hash = "$2b$12$Kk/BoZorZMjoCk3EW2sUmeDOhDO30I8jxmjyquVf0avtk18mhEnQO"
password_changed_at = "2025-10-13T12:00:12.652627900Z"
jwt_secret = "cloudtui-secret-8d8969910b1f805b"
