[package]
name = "cloudhost-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["sync", "rt", "rt-multi-thread"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
dirs = "5.0"
